version: '2.1'
services:
  app:
    image: lambci/lambda:python3.8
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID- }
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY- }
      - AWS_DEFAULT_REGION=ap-northeast-1
      - AWS_LAMBDA_FUNCTION_MEMORY_SIZE=1024
      - AWS_LAMBDA_FUNCTION_TIMEOUT=3600
    volumes:
      - ./:/var/task
    command: >
      lambda_function.lambda_handler
      '{
      }'
